/* Consulta - 05 - Pie Charts
   http://bl.ocks.org/mbostock/3887235#data.csv
		
   Isentos, Renda, Procêdência, Cursinho e Etnia serão Pie Chart?
   E serão em porcentagem? Não lembro. 
   Mas estou supondo que sim para as duas questões.
*/

-- Isentos
SELECT 'Sim' TIPO, 
	   ROUND(SUM(IF(CREL_ISENTO='S', 1, 0))/COUNT(1)*100, 1) PERCENT_ISENTO 
FROM CANDIDATO_RELATORIO
WHERE CREL_PROCESSO = '20111_integrado'
UNION
SELECT 'Não' TIPO, 
	   ROUND(SUM(IF(CREL_ISENTO='N', 1, 0))/COUNT(1)*100, 1) PERCENT_ISENTO 
FROM CANDIDATO_RELATORIO
WHERE CREL_PROCESSO = '20111_integrado'
ORDER BY TIPO DESC;

-- Renda
SELECT A1.REN_DESCRICAO, 
	   ROUND(SUM(IF(C.CREL_RENDA=A2.REN_LETRA, 1, 0))/T.TOTAL*100, 1) PERCENT_RENDA
FROM CANDIDATO_RELATORIO C, ALT_RENDA A1, ALT_RENDA A2,
 (SELECT COUNT(1) TOTAL FROM CANDIDATO_RELATORIO WHERE CREL_PROCESSO = '20111_integrado') T
WHERE C.CREL_RENDA = A1.REN_LETRA
AND CREL_PROCESSO = '20111_integrado'
GROUP BY C.CREL_RENDA
ORDER BY C.CREL_RENDA;

-- Procêdência 
SELECT A1.PROC_DESCRICAO, 
	   ROUND(SUM(IF(C.CREL_PROCEDENCIA=A2.PROC_LETRA, 1, 0))/T.TOTAL*100, 1) PERCENT_PROCEDENCIA
FROM CANDIDATO_RELATORIO C, ALT_PROCEDENCIA A1, ALT_PROCEDENCIA A2,
 (SELECT COUNT(1) TOTAL FROM CANDIDATO_RELATORIO WHERE CREL_PROCESSO = '20111_integrado') T
WHERE C.CREL_PROCEDENCIA = A1.PROC_LETRA
AND CREL_PROCESSO = '20111_integrado'
GROUP BY C.CREL_PROCEDENCIA
ORDER BY C.CREL_PROCEDENCIA;

-- Cursinho
SELECT 'Sim' TIPO, 
	   ROUND(SUM(IF(CREL_PRE_VESTIBULAR='S', 1, 0))/COUNT(1)*100, 1) PERCENT_CURSINHO 
FROM CANDIDATO_RELATORIO
WHERE CREL_PROCESSO = '20111_integrado'
UNION
SELECT 'Não' TIPO, 
	   ROUND(SUM(IF(CREL_PRE_VESTIBULAR='N', 1, 0))/COUNT(1)*100, 1) PERCENT_CURSINHO 
FROM CANDIDATO_RELATORIO
WHERE CREL_PROCESSO = '20111_integrado'
UNION
SELECT 'Não Declarou' TIPO, 
	   ROUND(SUM(IF(CREL_PRE_VESTIBULAR='S', 0, IF(CREL_PRE_VESTIBULAR='N', 0, 1)))/COUNT(1)*100, 1) PERCENT_CURSINHO 
FROM CANDIDATO_RELATORIO
WHERE CREL_PROCESSO = '20111_integrado';


-- Etnia
SELECT IF (A1.ETN_LETRA='F', 'Nao Declarou', A1.ETN_DESCRICAO) ETN_DESCRICAO,
	   ROUND(SUM(IF(C.CREL_ETNIA = A2.ETN_LETRA, 1, 0))/T.TOTAL*100, 1) PERCENT_ETNIA
FROM CANDIDATO_RELATORIO C, ALT_ETNIA A1, ALT_ETNIA A2,
 (SELECT COUNT(1) TOTAL FROM CANDIDATO_RELATORIO WHERE CREL_PROCESSO = '20111_integrado') T
WHERE C.CREL_ETNIA = A1.ETN_LETRA
AND CREL_PROCESSO = '20111_integrado'
GROUP BY ETN_DESCRICAO
ORDER BY C.CREL_ETNIA;

