/* Consulta - 06 - Histogram Chart - Por Matéria
   http://bl.ocks.org/mbostock/1933560
		
   Histogram Charts, um por matéria, para mostrar a porcentagem de questões acertadas?
*/

-- Português - Estatísticas do número de questões acertadas
SELECT CREL_PORTUGUES, ROUND(COUNT(1)/T.TOTAL*100,1) PERCENT_CANDIDATOS
FROM CANDIDATO_RELATORIO C,
	(SELECT COUNT(1) TOTAL
	FROM CANDIDATO_RELATORIO
	WHERE CREL_PROCESSO = '20111_integrado'
	AND CREL_CLASSIFICACAO > 0) T
WHERE CREL_PROCESSO = '20111_integrado'
AND CREL_CLASSIFICACAO > 0 -- fez a prova
GROUP BY CREL_PORTUGUES
ORDER BY CREL_PORTUGUES;

-- Matemática - Estatísticas do número de questões acertadas
SELECT CREL_MATEMATICA, ROUND(COUNT(1)/T.TOTAL*100,1) PERCENT_CANDIDATOS
FROM CANDIDATO_RELATORIO C,
	(SELECT COUNT(1) TOTAL
	FROM CANDIDATO_RELATORIO
	WHERE CREL_PROCESSO = '20111_integrado'
	AND CREL_CLASSIFICACAO > 0) T
WHERE CREL_PROCESSO = '20111_integrado'
AND CREL_CLASSIFICACAO > 0 -- fez a prova
GROUP BY CREL_MATEMATICA
ORDER BY CREL_MATEMATICA;

-- Física - Estatísticas do número de questões acertadas
SELECT CREL_FISICA, ROUND(COUNT(1)/T.TOTAL*100,1) PERCENT_CANDIDATOS
FROM CANDIDATO_RELATORIO C,
	(SELECT COUNT(1) TOTAL
	FROM CANDIDATO_RELATORIO
	WHERE CREL_PROCESSO = '20111_integrado'
	AND CREL_CLASSIFICACAO > 0) T
WHERE CREL_PROCESSO = '20111_integrado'
AND CREL_CLASSIFICACAO > 0 -- fez a prova
GROUP BY CREL_FISICA
ORDER BY CREL_FISICA;

-- Química - Estatísticas do número de questões acertadas
SELECT CREL_QUIMICA, ROUND(COUNT(1)/T.TOTAL*100,1) PERCENT_CANDIDATOS
FROM CANDIDATO_RELATORIO C,
	(SELECT COUNT(1) TOTAL
	FROM CANDIDATO_RELATORIO
	WHERE CREL_PROCESSO = '20111_integrado'
	AND CREL_CLASSIFICACAO > 0) T
WHERE CREL_PROCESSO = '20111_integrado'
AND CREL_CLASSIFICACAO > 0 -- fez a prova
GROUP BY CREL_QUIMICA
ORDER BY CREL_QUIMICA;

-- Biologia - Estatísticas do número de questões acertadas
SELECT CREL_BIOLOGIA, ROUND(COUNT(1)/T.TOTAL*100,1) PERCENT_CANDIDATOS
FROM CANDIDATO_RELATORIO C,
	(SELECT COUNT(1) TOTAL
	FROM CANDIDATO_RELATORIO
	WHERE CREL_PROCESSO = '20111_integrado'
	AND CREL_CLASSIFICACAO > 0) T
WHERE CREL_PROCESSO = '20111_integrado'
AND CREL_CLASSIFICACAO > 0 -- fez a prova
GROUP BY CREL_BIOLOGIA
ORDER BY CREL_BIOLOGIA;

-- História - Estatísticas do número de questões acertadas
SELECT CREL_HISTORIA, ROUND(COUNT(1)/T.TOTAL*100,1) PERCENT_CANDIDATOS
FROM CANDIDATO_RELATORIO C,
	(SELECT COUNT(1) TOTAL
	FROM CANDIDATO_RELATORIO
	WHERE CREL_PROCESSO = '20111_integrado'
	AND CREL_CLASSIFICACAO > 0) T
WHERE CREL_PROCESSO = '20111_integrado'
AND CREL_CLASSIFICACAO > 0 -- fez a prova
GROUP BY CREL_HISTORIA
ORDER BY CREL_HISTORIA;

-- Geografia - Estatísticas do número de questões acertadas
SELECT CREL_GEOGRAFICA, ROUND(COUNT(1)/T.TOTAL*100,1) PERCENT_CANDIDATOS
FROM CANDIDATO_RELATORIO C,
	(SELECT COUNT(1) TOTAL
	FROM CANDIDATO_RELATORIO
	WHERE CREL_PROCESSO = '20111_integrado'
	AND CREL_CLASSIFICACAO > 0) T
WHERE CREL_PROCESSO = '20111_integrado'
AND CREL_CLASSIFICACAO > 0 -- fez a prova
GROUP BY CREL_GEOGRAFICA
ORDER BY CREL_GEOGRAFICA;
