/* Consulta - 02 - Radar Chart
   http://www.larsko.org/v/euc/
   Traz o número de inscrições feitas por horário do dia. */

-- Radar por minuto
SELECT CONCAT(LPAD(HOUR(CREL_DATAINSCRICAO), 2, '0'), ':',
       LPAD(MINUTE(CREL_DATAINSCRICAO), 2, '0')) HORA_INSCRICAO, COUNT(1)
FROM CANDIDATO_RELATORIO 
WHERE CREL_DATAINSCRICAO > '2010-01-01'
GROUP BY HORA_INSCRICAO
ORDER BY HORA_INSCRICAO;

-- Diminuindo o detalhe para 10 minutos
SELECT 
  IF(ROUND(MINUTE(CREL_DATAINSCRICAO), -1)=60, 
  	 IF(HOUR(CREL_DATAINSCRICAO)=23, '00:00', CONCAT(LPAD(HOUR(CREL_DATAINSCRICAO)+1, 2, '0'), ':00')),
     CONCAT(LPAD(HOUR(CREL_DATAINSCRICAO), 2, '0'), ':', LPAD(ROUND(MINUTE(CREL_DATAINSCRICAO), -1), 2, '0'))) HORA_INSCRICAO,
  COUNT(1)
FROM CANDIDATO_RELATORIO 
WHERE CREL_DATAINSCRICAO > '2010-01-01'
GROUP BY HORA_INSCRICAO
ORDER BY HORA_INSCRICAO;
